### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by LvKang-insist** [AnyLifeZLB/CameraXFragment#3]
您好，我在使用的时候将 fragment 添加到了 viewpager2中，直接显示黑屏了，请问这是什么情况。我是使用的版本是 1.2.0

**Comment by AnyLifeZLB** [comment]
@LvKang-insist App有没有相机权限？放到view Pager我还没有试过，你先放到正常Activity 中试试，我觉得没有问题

**Comment by AnyLifeZLB** [comment]
或者把代码放到GitHub 我有空帮你看看
